apiVersion: apps/v1
kind:       Deployment
metadata:
  name: $APP
spec:
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      containers:
        - name:  $APP
          image: $IMAGE
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /is_alive
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /is_alive
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
